trigger:   # any changes in main branch will trigger the pipeline   
- main

pool:   # defines where our pipeline will be executed
    vmImage: 'macOS-latest'

stages:
- stage: BuildApp
  jobs:
  - job: macOS
    steps:
    - script: echo hello from macOS
