trigger:   # any changes in main branch will trigger the pipeline   
- main

pool:   # defines where our pipeline will be executed
  name: 'default'
  vmImage: 'SHUBH-PC'

stages:
- stage: BuildApp
  jobs:
  - job: windowsOS
    steps:
    - script: echo hello from macOS
